### ISSUE TITLE
在 VSCode 中打开第二个 byzer project  folder，不能work

### ISSUE THREAD

**Issue by ZhengshuaiPENG** [byzer-org/byzer-desktop#1]
当前 vscode 的插件只能支持打开一个 byzer project folder，不能打开第二个 byzer project，第二个 byzer project 打开后，各类文件都无法打开会报错

**Comment by ZhengshuaiPENG** [comment]
先看看原因，再评估是否修复

**Comment by synchronized15** [comment]
未能复现
